### ISSUE TITLE
allow piping into cabinetry cli

### ISSUE THREAD

**Issue by lukasheinrich** [alexander-held/cabinetry#141]
it'd be great if I could do the following

```
jsonpatch 1Lbb-likelihoods/BkgOnly.json <(pyhf patchset extract --name C1N2_Wh_hbb_900_300 1Lbb-likelihoods/patchset.json )|cabinetry fit -
```

in pyhf we support a standard linux convention that `-` represents "read from stdin"

Currently I need to do the following:

```
jsonpatch 1Lbb-likelihoods/BkgOnly.json <(pyhf patchset extract --name C1N2_Wh_hbb_900_300 1Lbb-likelihoods/patchset.json ) > a.json
cabinetry fit a.json
```

**Comment by alexander-held** [comment]
Thanks for the suggestion! This looks useful. I had a quick look at the [`click` documentation for file arguments](https://click.palletsprojects.com/en/7.x/arguments/#file-arguments) and it seems like switching to `click.File` enables the correct handling of `-`. That might require moving the json parsing into the CLI, since the currently responsible function uses `pathlib` (or slightly changing that function).

How are you handling this in `pyhf`?

**Comment by lukasheinrich** [comment]
we don't use `click.File` directly (maybe we should)  but we do 

```
    with click.open_file(workspace, "r") as specstream:
        spec = json.load(specstream)
```

and that works

https://github.com/scikit-hep/pyhf/blob/master/src/pyhf/cli/infer.py#L100

**Comment by alexander-held** [comment]
Reading config / workspaces from stdin, as well as writing workspaces to stdout, are now supported in the CLI with #143.
