### ISSUE TITLE
support for alternative backends for pyhf

### ISSUE THREAD

**Issue by mhance** [alexander-held/cabinetry#227]
I'm fitting some (probably unnecessarily) complex workspaces on a machine that happens to have a GPU, and I'd like to use the jax backend for pyhf to speed things up.  However, it seems that the numpy backend is hard coded in, e.g.:

https://github.com/alexander-held/cabinetry/blob/e6dca5e4a3814325fe5efa5f977a4f8dc43aa6d3/src/cabinetry/fit.py#L157
https://github.com/alexander-held/cabinetry/blob/e6dca5e4a3814325fe5efa5f977a4f8dc43aa6d3/src/cabinetry/fit.py#L218
https://github.com/alexander-held/cabinetry/blob/e6dca5e4a3814325fe5efa5f977a4f8dc43aa6d3/src/cabinetry/fit.py#L651
https://github.com/alexander-held/cabinetry/blob/e6dca5e4a3814325fe5efa5f977a4f8dc43aa6d3/src/cabinetry/fit.py#L829

Can this be configurable instead, or not explicitly set so the user can override it in a python steering script?  Any reason this is a bad idea?  Thanks!

**Comment by alexander-held** [comment]
Hi, thanks for bringing this up! There is no good reason to keep this current limitation. It was initially easier to guarantee `numpy` outputs from the fits for subsequent steps. That helped avoid having to deal with conversions needed when switching to other backends. I had a look at the `pyhf` API and it looks like it might be possible to use `pyhf.tensorlib.to_numpy` to convert tensors from all backends, which should be convenient for this purpose. I will give this a try.

In the end it should then be possible to use a pattern like this
```python
pyhf.set_backend("jax")
cabinetry.fit.fit(model, data)
```
and the `jax` setting would not be overridden, but the minimizer would get set to MINUIT anyway (since that is needed for some features).

**Comment by mhance** [comment]
Thanks Alex!  Sounds great.

**Comment by alexander-held** [comment]
Small update: testing this setup properly turned out more difficult than expected. #228 includes the relevant changes in the code to support other backends, but the test strategy still needs some work.

**Comment by alexander-held** [comment]
It has taken a while to resolve unrelated issues that came up in the meantime, but with #228 merged `cabinetry` now supports all `pyhf` backends. Backends can be set via `pyhf.set_backend` and are no longer overridden inside `cabinetry`.

I expect to release version `0.2.2` tomorrow including this change.

**Comment by mhance** [comment]
Fantastic, thanks a lot Alex!  Looking forward to testing this out.

**Comment by alexander-held** [comment]
`cabinetry` [0.2.2](https://github.com/alexander-held/cabinetry/releases/tag/v0.2.2) is now [available via PyPI](https://pypi.org/project/cabinetry/). Let me know if you run into any issues with the multi-backend support!
